#chain network
net: "livenet"


#database
database:
  indexer_type: "pebble"  # Indexer database type: mysql or pebble (uploader always uses mysql)
  dsn: "user:password@tcp(localhost:3306)/metaid_file_system_db?charset=utf8mb4&parseTime=True&loc=Local&timeout=5s&readTimeout=30s"
  max_open_conns: 1000
  max_idle_conns: 50
  data_dir: "./data/pebble"  # PebbleDB data directory (used when indexer_type=pebble)

# Indexer configuration
indexer:
  port: "7281"   # Indexer service port
  scan_interval: 10
  batch_size: 100
  start_height: 0  # If 0, will use chain-specific init height or database max height
  mvc_init_block_height: 350000  # MVC chain initial block height (used when start_height=0 and no data in DB)
  btc_init_block_height: 800000  # BTC chain initial block height (used when start_height=0 and no data in DB)
  doge_init_block_height: 4000000  # DOGE chain initial block height (used when start_height=0 and no data in DB)
  swagger_base_url: "localhost:7281"  # Swagger API base URL (shown in Swagger UI)
  zmq_enabled: false  # Enable ZMQ real-time monitoring
  zmq_address: "tcp://127.0.0.1:28332"  # ZMQ server address (for BTC/MVC node)
  large_block_size_mb: 200  # Blocks larger than this (MB) are loaded tx-by-tx to avoid OOM; 0 = 50
  # Multi-chain configuration (if configured, will use multi-chain mode)
  time_ordering_enabled: true  # Enable strict time ordering across chains
  chains:
    - name: "mvc"
      rpc_url: "http://127.0.0.1:9882"
      rpc_user: "rpcuser"
      rpc_pass: "rpcpassword"
      start_height: 350000
      zmq_enabled: true
      zmq_address: "tcp://127.0.0.1:28332"
    - name: "btc"
      rpc_url: "http://127.0.0.1:8332"
      rpc_user: "btcuser"
      rpc_pass: "btcpass"
      start_height: 800000
      zmq_enabled: true
      zmq_address: "tcp://127.0.0.1:28333"
    - name: "doge"
      rpc_url: "http://127.0.0.1:22555"
      rpc_user: "dogeuser"
      rpc_pass: "dogepass"
      start_height: 4000000
      zmq_enabled: true
      zmq_address: "tcp://127.0.0.1:28334"

# Uploader configuration
uploader:
  port: "7282"  # Uploader service port
  max_file_size: 100 # MB (global default)
  chunk_size: 2      # MB (global default)
  fee_rate: 1
  swagger_base_url: "localhost:7282"  # Swagger API base URL (shown in Swagger UI)
  # RpcConfigMap and per-chain params are populated from uploader.chains (not indexer.chains)
  chains:
    - name: "mvc"
      rpc_url: "http://127.0.0.1:9882"
      rpc_user: "rpcuser"
      rpc_pass: "rpcpassword"
      max_file_size: 100  # MB, optional
      chunk_size: 2       # MB, optional
      fee_rate: 1         # sat/byte
    - name: "doge"
      rpc_url: "http://127.0.0.1:22555"
      rpc_user: "dogeuser"
      rpc_pass: "dogepass"
      max_file_size: 100
      chunk_size_bytes: 1200  # DOGE max chunk size in bytes
      fee_rate: 200000    # sat/KB for DOGE

# Blockchain configuration
chain:
  rpc_url: "http://127.0.0.1:9882"
  rpc_user: "rpcuser"
  rpc_pass: "rpcpassword"
  start_height: 0

# Storage configuration
storage:
  type: "local"  # local/oss/s3/minio
  local:
    base_path: "./data/files"
  oss:
    endpoint: ""
    access_key: ""
    secret_key: ""
    bucket: ""
    domain: ""
  s3:
    region: "us-east-1"
    endpoint: ""  # Optional custom endpoint (leave empty for AWS S3)
    access_key: ""
    secret_key: ""
    bucket: ""
    domain: ""
  minio:
    endpoint: "http://localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "meta-file-system"
    use_ssl: false
    domain: ""

# Redis configuration
redis:
  enabled: true  # Enable Redis cache for user info
  host: "redis"  # Use "redis" when running in Docker Compose
  port: 6379  # Use internal port 6379 (not 6380) when running in Docker Compose
  password: ""  # Empty for no password
  db: 1
  cache_ttl: 1800  # Cache TTL in seconds (30 minutes)


