// Package uploader Code generated by swaggo/swag. DO NOT EDIT
package uploader

import "github.com/swaggo/swag"

const docTemplateuploader = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "description": "Get upload service configuration information, including max file size and swagger base URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration"
                ],
                "summary": "Get configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller_handler.ConfigResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/files/chunked-upload": {
            "post": {
                "description": "Upload large file by splitting it into chunks, build transactions for chunks and index, optionally broadcast all transactions in order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Chunked file upload",
                "parameters": [
                    {
                        "description": "Chunked upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller_handler.ChunkedUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_service_upload_service.ChunkedUploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parameter error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/chunked-upload-task": {
            "post": {
                "description": "Create an async chunked upload task and return the task ID so the client can poll for progress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Async chunked upload (create task)",
                "parameters": [
                    {
                        "description": "Async chunked upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller_handler.ChunkedUploadForTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.ChunkedUploadTaskResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/commit-upload": {
            "post": {
                "description": "Submit signed transaction for broadcast",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Commit upload",
                "parameters": [
                    {
                        "description": "Commit upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller_handler.CommitUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload successful, return transaction ID and Pin ID",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller_handler.CommitUploadResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parameter error or file not found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error or broadcast failed",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/direct-upload": {
            "post": {
                "description": "Upload file and add MetaID OP_RETURN output to existing PreTxHex, then broadcast immediately. This is a one-step upload process that combines building and broadcasting. Supports UTXO merge transaction for SIGHASH_SINGLE compatibility.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Direct upload file (one-step)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pre-transaction hex (signed, with inputs and outputs)",
                        "name": "preTxHex",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Merge transaction hex (optional, broadcasted before main transaction)",
                        "name": "mergeTxHex",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "create",
                        "description": "Operation type",
                        "name": "operation",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Content type",
                        "name": "contentType",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Address (also used as change address if changeAddress is not provided)",
                        "name": "address",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Change address (optional, defaults to address)",
                        "name": "changeAddress",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Fee rate (satoshis per byte, optional)",
                        "name": "feeRate",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Total input amount in satoshis (optional, for automatic change calculation)",
                        "name": "totalInputAmount",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload successful, return transaction ID and Pin ID",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller_handler.CommitUploadResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parameter error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/estimate-chunked-upload": {
            "post": {
                "description": "Estimate the fee required for chunked file upload, including chunk count and fees for ChunkPreTxHex and IndexPreTxHex",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Estimate chunked upload fee",
                "parameters": [
                    {
                        "description": "Estimate chunked upload request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller_handler.EstimateChunkedUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Estimate successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_service_upload_service.EstimateChunkedUploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parameter error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/pre-upload": {
            "post": {
                "description": "Upload file and generate unsigned transaction, return transaction for client signing",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Pre-upload file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "create",
                        "description": "Operation type",
                        "name": "operation",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Content type",
                        "name": "contentType",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Change address",
                        "name": "changeAddress",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Fee rate",
                        "name": "feeRate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Output list json",
                        "name": "outputs",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Other output list json",
                        "name": "otherOutputs",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pre-upload successful, return transaction and file info",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller_handler.PreUploadResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parameter error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/task/{taskId}": {
            "get": {
                "description": "Get async upload task progress and status by task ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Query task progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.UploadTaskDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid parameter",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/tasks": {
            "get": {
                "description": "List chunked upload tasks for a given address with cursor-based pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "List upload tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor (last task ID)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.UploadTaskListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Parameter error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller_handler.ChunkedUploadForTaskRequest": {
            "type": "object",
            "required": [
                "address",
                "chunkPreTxHex",
                "content",
                "fileName",
                "indexPreTxHex",
                "metaId",
                "path"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "chunkPreTxHex": {
                    "type": "string",
                    "example": "0100000..."
                },
                "content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "feeRate": {
                    "type": "integer",
                    "example": 1
                },
                "fileName": {
                    "type": "string",
                    "example": "example.jpg"
                },
                "indexPreTxHex": {
                    "type": "string",
                    "example": "0100000..."
                },
                "mergeTxHex": {
                    "type": "string",
                    "example": "0100000..."
                },
                "metaId": {
                    "type": "string",
                    "example": "metaid_abc123"
                },
                "operation": {
                    "type": "string",
                    "example": "create"
                },
                "path": {
                    "type": "string",
                    "example": "/file"
                }
            }
        },
        "controller_handler.ChunkedUploadRequest": {
            "type": "object",
            "required": [
                "address",
                "chunkPreTxHex",
                "content",
                "fileName",
                "indexPreTxHex",
                "metaId",
                "path"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "chunkPreTxHex": {
                    "type": "string",
                    "example": "0100000..."
                },
                "content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "feeRate": {
                    "type": "integer",
                    "example": 1
                },
                "fileName": {
                    "type": "string",
                    "example": "example.jpg"
                },
                "indexPreTxHex": {
                    "type": "string",
                    "example": "0100000..."
                },
                "isBroadcast": {
                    "type": "boolean",
                    "example": false
                },
                "mergeTxHex": {
                    "type": "string",
                    "example": "0100000..."
                },
                "metaId": {
                    "type": "string",
                    "example": "metaid_abc123"
                },
                "operation": {
                    "type": "string",
                    "example": "create"
                },
                "path": {
                    "type": "string",
                    "example": "/file"
                }
            }
        },
        "controller_handler.CommitUploadRequest": {
            "type": "object",
            "required": [
                "fileId",
                "signedRawTx"
            ],
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "metaid_abc123"
                },
                "signedRawTx": {
                    "type": "string",
                    "example": "0100000..."
                }
            }
        },
        "controller_handler.CommitUploadResponseData": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "metaid_abc123"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "pinId": {
                    "type": "string",
                    "example": "abc123...i0"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "txId": {
                    "type": "string",
                    "example": "abc123..."
                }
            }
        },
        "controller_handler.ConfigResponse": {
            "type": "object",
            "properties": {
                "maxFileSize": {
                    "type": "integer",
                    "example": 10485760
                },
                "swaggerBaseUrl": {
                    "type": "string",
                    "example": "localhost:7282"
                }
            }
        },
        "controller_handler.EstimateChunkedUploadRequest": {
            "type": "object",
            "required": [
                "content",
                "fileName",
                "path"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "feeRate": {
                    "type": "integer",
                    "example": 1
                },
                "fileName": {
                    "type": "string",
                    "example": "example.jpg"
                },
                "path": {
                    "type": "string",
                    "example": "/file"
                }
            }
        },
        "controller_handler.PreUploadResponseData": {
            "type": "object",
            "properties": {
                "calTxFee": {
                    "type": "integer",
                    "example": 1000
                },
                "calTxSize": {
                    "type": "integer",
                    "example": 500
                },
                "fileId": {
                    "type": "string",
                    "example": "metaid_abc123"
                },
                "fileMd5": {
                    "type": "string",
                    "example": "5d41402abc4b2a76b9719d911017c592"
                },
                "filehash": {
                    "type": "string",
                    "example": "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "pinId": {
                    "type": "string",
                    "example": "abc123...i0"
                },
                "preTxRaw": {
                    "type": "string",
                    "example": "0100000..."
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "txId": {
                    "type": "string",
                    "example": "abc123..."
                }
            }
        },
        "meta-file-system_controller_respond.ChunkedUploadTaskResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "task created"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "taskId": {
                    "type": "string",
                    "example": "task_123"
                }
            }
        },
        "meta-file-system_controller_respond.Response": {
            "description": "Unified API response structure",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "processingTime": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "meta-file-system_controller_respond.UploadTask": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "chunkFundingTx": {
                    "type": "string"
                },
                "chunkTxIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "contentType": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentStep": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "fileHash": {
                    "type": "string"
                },
                "fileId": {
                    "type": "string"
                },
                "fileMd5": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "finishedAt": {
                    "type": "string"
                },
                "indexTxId": {
                    "type": "string"
                },
                "metaId": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "processedChunks": {
                    "type": "integer"
                },
                "progress": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                },
                "totalChunks": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "meta-file-system_controller_respond.UploadTaskDetailResponse": {
            "type": "object",
            "properties": {
                "task": {
                    "$ref": "#/definitions/meta-file-system_controller_respond.UploadTask"
                }
            }
        },
        "meta-file-system_controller_respond.UploadTaskListResponse": {
            "type": "object",
            "properties": {
                "hasMore": {
                    "type": "boolean",
                    "example": true
                },
                "nextCursor": {
                    "type": "integer",
                    "example": 123
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/meta-file-system_controller_respond.UploadTask"
                    }
                }
            }
        },
        "meta-file-system_service_upload_service.ChunkedUploadResponse": {
            "type": "object",
            "properties": {
                "chunkFundingTx": {
                    "description": "Funding transaction for chunk outputs",
                    "type": "string"
                },
                "chunkNumber": {
                    "description": "Number of chunks",
                    "type": "integer"
                },
                "chunkTxIds": {
                    "description": "Chunk transaction IDs (ordered)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "chunkTxs": {
                    "description": "Chunk transaction hex list (ordered)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fileHash": {
                    "description": "File SHA256 hash",
                    "type": "string"
                },
                "fileId": {
                    "description": "File ID",
                    "type": "string"
                },
                "fileMd5": {
                    "description": "File MD5 hash",
                    "type": "string"
                },
                "indexTx": {
                    "description": "Index transaction hex",
                    "type": "string"
                },
                "indexTxId": {
                    "description": "Index transaction ID",
                    "type": "string"
                },
                "message": {
                    "description": "Additional message",
                    "type": "string"
                },
                "status": {
                    "description": "Status string",
                    "type": "string"
                }
            }
        },
        "meta-file-system_service_upload_service.EstimateChunkedUploadResponse": {
            "type": "object",
            "properties": {
                "chunkFees": {
                    "description": "Fee per chunk",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chunkNumber": {
                    "description": "Number of chunks",
                    "type": "integer"
                },
                "chunkPerTxFee": {
                    "description": "Fee required per chunk transaction",
                    "type": "integer"
                },
                "chunkPreTxFee": {
                    "description": "Total funding required for chunk transactions",
                    "type": "integer"
                },
                "chunkSize": {
                    "description": "Chunk size in bytes",
                    "type": "integer"
                },
                "indexPreTxFee": {
                    "description": "Funding required for the index transaction",
                    "type": "integer"
                },
                "message": {
                    "description": "Additional message",
                    "type": "string"
                },
                "perChunkFee": {
                    "description": "Average fee per chunk",
                    "type": "integer"
                },
                "totalFee": {
                    "description": "Total fee (ChunkPreTxFee + IndexPreTxFee)",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfouploader holds exported Swagger Info so clients can modify it
var SwaggerInfouploader = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7282",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Meta File System Uploader API",
	Description:      "Meta File System Upload Service API, provides file upload functionality",
	InfoInstanceName: "uploader",
	SwaggerTemplate:  docTemplateuploader,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfouploader.InstanceName(), SwaggerInfouploader)
}
