// Package indexer Code generated by swaggo/swag. DO NOT EDIT
package indexer

import "github.com/swaggo/swag"

const docTemplateindexer = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/rescan": {
            "post": {
                "description": "Trigger asynchronous rescan of blocks within specified height range for a specific chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Admin"
                ],
                "summary": "Rescan blocks",
                "parameters": [
                    {
                        "description": "Rescan request parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.RescanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.RescanResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/admin/rescan/status": {
            "get": {
                "description": "Get current rescan task status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Admin"
                ],
                "summary": "Get rescan status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.RescanStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/admin/rescan/stop": {
            "post": {
                "description": "Stop the current rescan task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Admin"
                ],
                "summary": "Stop rescan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.RescanStopResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files": {
            "get": {
                "description": "Query file list with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Query file list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerFileListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/accelerate/content/latest/{firstPinId}": {
            "get": {
                "description": "Redirect to OSS URL for latest file content by first PIN ID, supports preview/thumbnail/video processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get latest accelerated file content (redirect to OSS)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "First PIN ID",
                        "name": "firstPinId",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Process type: preview (640px for image), thumbnail (235px for image), video (first frame for video), empty for original",
                        "name": "process",
                        "in": "query"
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to OSS URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/accelerate/content/{pinId}": {
            "get": {
                "description": "Redirect to OSS URL for file content by PIN ID, supports preview/thumbnail/video processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get accelerated file content (redirect to OSS)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Process type: preview (640px for image), thumbnail (235px for image), video (first frame for video), empty for original",
                        "name": "process",
                        "in": "query"
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to OSS URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/content/latest/{firstPinId}": {
            "get": {
                "description": "Get latest file content by first PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get latest file content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "First PIN ID",
                        "name": "firstPinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/content/{pinId}": {
            "get": {
                "description": "Get file content by PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get file content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/creator/{address}": {
            "get": {
                "description": "Query file list by creator address with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get files by creator address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Creator address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerFileListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/latest/{firstPinId}": {
            "get": {
                "description": "Query latest file details by first PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get latest file by first PIN ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "First PIN ID",
                        "name": "firstPinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerFileResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/metaid/{metaId}": {
            "get": {
                "description": "Query file list by creator MetaID with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get files by creator MetaID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Creator MetaID",
                        "name": "metaId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerFileListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/{pinId}": {
            "get": {
                "description": "Query file details by PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get file by PIN ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerFileResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/info/address/{address}": {
            "get": {
                "description": "Query user information in MetaID format by address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get MetaID user info by address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.MetaIDUserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/info/metaid/{metaid}": {
            "get": {
                "description": "Query user information in MetaID format by MetaID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get MetaID user info by MetaID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.MetaIDUserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/info/search": {
            "get": {
                "description": "Fuzzy search user information by keyword and keytype (metaid or name)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Search MetaID user info (fuzzy)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (partial MetaID or Name)",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Key type: metaid (fuzzy) or name (fuzzy)",
                        "name": "keytype",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Result limit (default: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/meta-file-system_controller_respond.MetaIDUserInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/pins/{pinId}": {
            "get": {
                "description": "Query PIN details from collectionPinInfo by PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer PIN Query"
                ],
                "summary": "Get PIN info by PIN ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerPinInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Get indexer statistics (total files count and per-chain breakdown)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Status"
                ],
                "summary": "Get statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get current sync status for all chains (current sync height and latest block height)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Status"
                ],
                "summary": "Get sync status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.IndexerMultiChainSyncStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/thumbnail/{pinId}": {
            "get": {
                "description": "Redirect to OSS URL for avatar thumbnail (128x128) by avatar PIN ID using OSS built-in thumbnail processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get avatar thumbnail (redirect to OSS)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Avatar PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to OSS URL with thumbnail processing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Query user info list with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Query user info list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-file-system_controller_respond.UserInfoListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users/address/{address}": {
            "get": {
                "description": "Query user information (name, avatar, chat public key) by address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get user info by address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.IndexerUserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users/avatar/accelerate/{pinId}": {
            "get": {
                "description": "Redirect to OSS URL for avatar content by avatar PIN ID, supports preview/thumbnail processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get accelerated avatar content (redirect to OSS)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Avatar PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Process type: preview (640px), thumbnail (128px), empty for original",
                        "name": "process",
                        "in": "query"
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to OSS URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users/avatar/content/{pinId}": {
            "get": {
                "description": "Get specific avatar version content by avatar PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get avatar content by PIN ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Avatar PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avatar content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users/history/{key}": {
            "get": {
                "description": "Get all user info history (name, avatar, chat public key) by MetaID or Address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get user info history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MetaID or Address",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.UserInfoHistory"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users/metaid/{metaId}": {
            "get": {
                "description": "Query user information (name, avatar, chat public key) by MetaID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get user info by MetaID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.IndexerUserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/users/metaid/{metaId}/avatar": {
            "get": {
                "description": "Get avatar content by user MetaID, returns content from storage or redirects to OSS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Indexer User Info"
                ],
                "summary": "Get avatar content by MetaID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User MetaID",
                        "name": "metaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Avatar content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "307": {
                        "description": "Redirect to OSS URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-file-system_controller_respond.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "meta-file-system_controller_respond.IndexerFileListResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/meta-file-system_controller_respond.IndexerFileResponse"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "meta-file-system_controller_respond.IndexerFileResponse": {
            "type": "object",
            "properties": {
                "block_height": {
                    "type": "integer",
                    "example": 12345
                },
                "chain_name": {
                    "type": "string",
                    "example": "mvc"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "creator_address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "creator_meta_id": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "encryption": {
                    "type": "string",
                    "example": "0"
                },
                "file_extension": {
                    "type": "string",
                    "example": ".jpg"
                },
                "file_hash": {
                    "type": "string",
                    "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
                },
                "file_md5": {
                    "type": "string",
                    "example": "d41d8cd98f00b204e9800998ecf8427e"
                },
                "file_name": {
                    "type": "string",
                    "example": "test.jpg"
                },
                "file_size": {
                    "type": "integer",
                    "example": 102400
                },
                "file_type": {
                    "type": "string",
                    "example": "image"
                },
                "operation": {
                    "type": "string",
                    "example": "create"
                },
                "owner_address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "owner_meta_id": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "path": {
                    "type": "string",
                    "example": "/file/test.jpg"
                },
                "pin_id": {
                    "description": "ID             int64     ` + "`" + `json:\"id\" example:\"1\"` + "`" + `",
                    "type": "string",
                    "example": "abc123def456i0"
                },
                "storage_path": {
                    "description": "StorageType    string    ` + "`" + `json:\"storage_type\" example:\"oss\"` + "`" + `",
                    "type": "string",
                    "example": "indexer/mvc/pinid123i0.jpg"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1699999999
                },
                "tx_id": {
                    "type": "string",
                    "example": "abc123def456789"
                }
            }
        },
        "meta-file-system_controller_respond.IndexerMultiChainSyncStatusResponse": {
            "type": "object",
            "properties": {
                "chains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/meta-file-system_controller_respond.IndexerSyncStatusResponse"
                    }
                }
            }
        },
        "meta-file-system_controller_respond.IndexerPinInfoResponse": {
            "type": "object",
            "properties": {
                "block_height": {
                    "type": "integer",
                    "example": 12345
                },
                "chain_name": {
                    "type": "string",
                    "example": "mvc"
                },
                "content_type": {
                    "type": "string",
                    "example": "text/plain"
                },
                "first_path": {
                    "type": "string",
                    "example": "/protocols/simplebuzz/info/name"
                },
                "first_pin_id": {
                    "type": "string",
                    "example": "xyz789i0"
                },
                "operation": {
                    "type": "string",
                    "example": "modify"
                },
                "path": {
                    "type": "string",
                    "example": "@xyz789i0"
                },
                "pin_id": {
                    "type": "string",
                    "example": "abc123def456i0"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1699999999
                }
            }
        },
        "meta-file-system_controller_respond.IndexerStatsResponse": {
            "type": "object",
            "properties": {
                "chain_stats": {
                    "description": "Per-chain file counts",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "total_files": {
                    "type": "integer",
                    "example": 12345
                }
            }
        },
        "meta-file-system_controller_respond.IndexerSyncStatusResponse": {
            "type": "object",
            "properties": {
                "chain_name": {
                    "description": "ID                int64     ` + "`" + `json:\"id\" example:\"1\"` + "`" + `",
                    "type": "string",
                    "example": "mvc"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "current_sync_height": {
                    "type": "integer",
                    "example": 12345
                },
                "latest_block_height": {
                    "type": "integer",
                    "example": 12350
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "meta-file-system_controller_respond.MetaIDUserInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "avatar": {
                    "type": "string",
                    "example": "https://oss.example.com/avatar.jpg"
                },
                "avatarId": {
                    "type": "string",
                    "example": "xyz789i0"
                },
                "chatpubkey": {
                    "type": "string",
                    "example": "02abc123..."
                },
                "chatpubkeyId": {
                    "type": "string",
                    "example": "def456i0"
                },
                "metaid": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "meta-file-system_controller_respond.RescanRequest": {
            "type": "object",
            "required": [
                "chain",
                "end_height",
                "start_height"
            ],
            "properties": {
                "chain": {
                    "type": "string",
                    "example": "mvc"
                },
                "end_height": {
                    "type": "integer",
                    "example": 100100
                },
                "start_height": {
                    "type": "integer",
                    "example": 100000
                }
            }
        },
        "meta-file-system_controller_respond.RescanResponse": {
            "type": "object",
            "properties": {
                "chain": {
                    "type": "string",
                    "example": "mvc"
                },
                "end_height": {
                    "type": "integer",
                    "example": 100100
                },
                "message": {
                    "type": "string",
                    "example": "Block rescan task started successfully"
                },
                "start_height": {
                    "type": "integer",
                    "example": 100000
                },
                "task_id": {
                    "type": "string",
                    "example": "rescan_mvc_100000_100100_1699999999"
                }
            }
        },
        "meta-file-system_controller_respond.RescanStatusResponse": {
            "type": "object",
            "properties": {
                "chain": {
                    "type": "string",
                    "example": "mvc"
                },
                "current_height": {
                    "type": "integer",
                    "example": 100050
                },
                "elapsed_time": {
                    "description": "milliseconds",
                    "type": "integer",
                    "example": 4050
                },
                "end_height": {
                    "type": "integer",
                    "example": 100100
                },
                "error_message": {
                    "type": "string",
                    "example": ""
                },
                "estimated_time_left": {
                    "description": "milliseconds",
                    "type": "integer",
                    "example": 4100
                },
                "processed_blocks": {
                    "type": "integer",
                    "example": 50
                },
                "progress": {
                    "description": "percentage",
                    "type": "number",
                    "example": 49.5
                },
                "speed": {
                    "description": "blocks per second",
                    "type": "number",
                    "example": 12.34
                },
                "start_height": {
                    "type": "integer",
                    "example": 100000
                },
                "start_time": {
                    "type": "integer",
                    "example": 1699999999
                },
                "status": {
                    "description": "idle, running, completed, cancelled, failed",
                    "type": "string",
                    "example": "running"
                },
                "task_id": {
                    "type": "string",
                    "example": "rescan_mvc_100000_100100_1699999999"
                },
                "total_blocks": {
                    "type": "integer",
                    "example": 101
                }
            }
        },
        "meta-file-system_controller_respond.RescanStopResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Rescan task stopped successfully"
                },
                "status": {
                    "type": "string",
                    "example": "cancelled"
                },
                "task_id": {
                    "type": "string",
                    "example": "rescan_mvc_100000_100100_1699999999"
                }
            }
        },
        "meta-file-system_controller_respond.Response": {
            "description": "Unified API response structure",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "processingTime": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "meta-file-system_controller_respond.UserInfoListResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "integer",
                    "example": 100
                },
                "total": {
                    "description": "Total number of users",
                    "type": "integer",
                    "example": 1000
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IndexerUserInfo"
                    }
                }
            }
        },
        "model.IndexerUserInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "用户地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "头像路径",
                    "type": "string"
                },
                "avatarPinId": {
                    "description": "头像 PIN ID",
                    "type": "string"
                },
                "blockHeight": {
                    "description": "区块高度",
                    "type": "integer"
                },
                "chainName": {
                    "description": "链名称",
                    "type": "string"
                },
                "chatPublicKey": {
                    "description": "聊天公钥",
                    "type": "string"
                },
                "chatPublicKeyPinId": {
                    "description": "聊天公钥 PIN ID",
                    "type": "string"
                },
                "metaId": {
                    "description": "用户 MetaID",
                    "type": "string"
                },
                "name": {
                    "description": "用户名称",
                    "type": "string"
                },
                "namePinId": {
                    "description": "用户名称 PIN ID",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer"
                }
            }
        },
        "model.UserAvatarInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像路径",
                    "type": "string"
                },
                "avatarUrl": {
                    "description": "头像 URL",
                    "type": "string"
                },
                "blockHeight": {
                    "description": "区块高度",
                    "type": "integer"
                },
                "chainName": {
                    "description": "链名称",
                    "type": "string"
                },
                "contentType": {
                    "description": "Content type (e.g., image/jpeg)",
                    "type": "string"
                },
                "fileExtension": {
                    "description": "File extension, e.g. .jpg, .png, .mp4, .mp3, .doc, .pdf, etc.",
                    "type": "string"
                },
                "fileHash": {
                    "description": "File Hash SHA256",
                    "type": "string"
                },
                "fileMd5": {
                    "description": "File MD5 hash",
                    "type": "string"
                },
                "fileSize": {
                    "description": "File size (bytes)",
                    "type": "integer"
                },
                "fileType": {
                    "description": "File type (image/video/audio/document/other)",
                    "type": "string"
                },
                "firstPath": {
                    "description": "第一个 PIN 的路径",
                    "type": "string"
                },
                "firstPinId": {
                    "description": "第一个 PIN ID",
                    "type": "string"
                },
                "pinId": {
                    "description": "PIN ID",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer"
                }
            }
        },
        "model.UserChatPublicKeyInfo": {
            "type": "object",
            "properties": {
                "blockHeight": {
                    "description": "区块高度",
                    "type": "integer"
                },
                "chainName": {
                    "description": "链名称",
                    "type": "string"
                },
                "chatPublicKey": {
                    "description": "聊天公钥",
                    "type": "string"
                },
                "firstPath": {
                    "description": "第一个 PIN 的路径",
                    "type": "string"
                },
                "firstPinId": {
                    "description": "第一个 PIN ID",
                    "type": "string"
                },
                "pinId": {
                    "description": "PIN ID",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer"
                }
            }
        },
        "model.UserInfoHistory": {
            "type": "object",
            "properties": {
                "avatarHistory": {
                    "description": "用户头像历史记录",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserAvatarInfo"
                    }
                },
                "chatPublicKeyHistory": {
                    "description": "用户聊天公钥历史记录",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserChatPublicKeyInfo"
                    }
                },
                "nameHistory": {
                    "description": "用户名称历史记录",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserNameInfo"
                    }
                }
            }
        },
        "model.UserNameInfo": {
            "type": "object",
            "properties": {
                "blockHeight": {
                    "description": "区块高度",
                    "type": "integer"
                },
                "chainName": {
                    "description": "链名称",
                    "type": "string"
                },
                "firstPath": {
                    "description": "第一个 PIN 的路径",
                    "type": "string"
                },
                "firstPinId": {
                    "description": "第一个 PIN ID",
                    "type": "string"
                },
                "name": {
                    "description": "用户名称",
                    "type": "string"
                },
                "pinId": {
                    "description": "PIN ID",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfoindexer holds exported Swagger Info so clients can modify it
var SwaggerInfoindexer = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7281",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Meta File System Indexer API",
	Description:      "Meta File System Indexer Service API, provides file query and download functionality",
	InfoInstanceName: "indexer",
	SwaggerTemplate:  docTemplateindexer,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoindexer.InstanceName(), SwaggerInfoindexer)
}
